### ISSUE TITLE
ctx.delete doesn't return deleted value

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer-context#14]
When doing

```ruby
form = ctx.delete(:form) #=> nil
```

the return value is `nil`. Maybe we shouldn't provide `#delete` in the first place?

**Comment by yogeshjain999** [comment]
> Maybe we shouldn't provide #delete in the first place?

hmm good point. Although, `ctx` is intended to work as extension over hash, yeah ?

PS: Fix is #15

**Comment by yogeshjain999** [comment]
Released in 0.5.1 🍻
